services:
  ci:
    container_name: nudebomb-ci
    entrypoint:
      - sleep
      - infinity
    environment:
      - PYTHONUNBUFFERED=1
    image: ghcr.io/nudebomb-ci
    volumes:
      - ./test-results:/app/test-results
      - ./dist:/app/dist
