"""What nudebomb records in timestamp files and when it invalidates them."""

import os
from hashlib import sha256
from pathlib import Path

import pytest
from treestamps import Grovestamps
from treestamps.tree.config import TreestampsConfig

from nudebomb.cli import get_arguments
from nudebomb.config import (
    RETIRED_TIMESTAMPS_CONFIG_DEFAULTS,
    TIMESTAMPS_CONFIG_DEFAULTS,
    TIMESTAMPS_CONFIG_KEYS,
    NudebombConfig,
)
from nudebomb.version import PROGRAM_NAME
from nudebomb.walk import Walk

__all__ = ()

TS_FN = f".{PROGRAM_NAME}_treestamps.yaml"

# Recorded keys whose effective value comes from a normalizer at run time
# rather than from the packaged defaults file.
_RESOLVED_KEYS = frozenset({"languages", "mkvmerge_bin"})


@pytest.fixture(autouse=True)
def isolate_config(monkeypatch, tmp_path):
    """Point confuse at an empty config dir and scrub nudebomb env vars."""
    for key in list(os.environ):
        if key.startswith("NUDEBOMB"):
            monkeypatch.delenv(key, raising=False)
    monkeypatch.setenv("NUDEBOMBDIR", str(tmp_path / "config"))


def _walk(media: Path, *extra_argv: str) -> Walk:
    media.mkdir(parents=True, exist_ok=True)
    argv = ("nudebomb", "-r", "-t", *extra_argv, "-l", "eng", str(media))
    args = get_arguments(argv)
    config = NudebombConfig().get_config(args)
    return Walk(config, args)


def _stamps(walk: Walk) -> Grovestamps:
    """Read the timestamp stores, asserting one was built."""
    walk._read_timestamps()
    assert walk._timestamps is not None
    return walk._timestamps


class TestRecordedConfig:
    """The program config recorded in stamp files."""

    def test_records_only_allowlisted_keys(self, tmp_path) -> None:
        """Secrets and run-scoped options must never reach the stamp file."""
        media = tmp_path / "media"
        tree = _stamps(_walk(media))[media]
        assert tree._config.program_config is not None
        recorded = set(tree._config.program_config)
        assert recorded == TIMESTAMPS_CONFIG_KEYS | {"_dir_config_fingerprint"}
        assert "tmdb_api_key" not in recorded
        assert "tvdb_api_key" not in recorded
        assert "paths" not in recorded

    def test_ignore_is_recorded(self) -> None:
        """Treestamps stopped recording ignore in 5.0.0, so nudebomb must."""
        assert "ignore" in TIMESTAMPS_CONFIG_KEYS

    def test_stamp_file_has_header_and_no_legacy_block(self, tmp_path) -> None:
        """Generated files explain themselves and omit the retired block."""
        media = tmp_path / "media"
        stamps = _stamps(_walk(media))
        stamps.set(media, media / "a.mkv", 100.0)
        stamps.dumpf()
        text = (media / TS_FN).read_text()
        assert text.startswith("# @generated by treestamps ")
        assert PROGRAM_NAME in text.splitlines()[0]
        assert "Safe to delete" in text
        assert "treestamps_config" not in text


class TestConfigDefaults:
    """Guard the defaults map against drift."""

    def test_covers_exactly_the_recorded_keys(self) -> None:
        """Every recorded key needs a default; nothing else belongs."""
        assert set(TIMESTAMPS_CONFIG_DEFAULTS) == set(TIMESTAMPS_CONFIG_KEYS)

    def test_retired_keys_are_no_longer_recorded(self) -> None:
        """A key cannot be both recorded and retired."""
        assert not set(RETIRED_TIMESTAMPS_CONFIG_DEFAULTS) & set(TIMESTAMPS_CONFIG_KEYS)

    @pytest.mark.parametrize("key", sorted(_RESOLVED_KEYS))
    def test_resolved_keys_have_no_usable_default(self, key: str) -> None:
        """
        Some keys get their effective value from a normalizer, not the yaml.

        Languages is required on the command line, and mkvmerge_bin is
        discovered on the host, so neither has a packaged default a stamp
        file could be compared against. Their default stays null, which makes
        a stamp file missing the key always invalidate — the safe answer,
        since nothing records what value it was written with.
        """
        assert TIMESTAMPS_CONFIG_DEFAULTS[key] is None

    def test_match_a_resolved_default_run(self, tmp_path) -> None:
        """
        The defaults must equal what a run actually resolves.

        Treestamps treats a key missing from a stamp file as holding its
        default, so a drifted default would wrongly keep or wrongly discard
        old stamp files.
        """
        media = tmp_path / "media"
        media.mkdir()
        args = get_arguments(("nudebomb", "-l", "eng", str(media)))
        settings = NudebombConfig().get_config(args)
        defaulted_keys = TIMESTAMPS_CONFIG_KEYS - _RESOLVED_KEYS
        resolved = {key: getattr(settings, key) for key in defaulted_keys}
        expected = {key: TIMESTAMPS_CONFIG_DEFAULTS[key] for key in defaulted_keys}
        assert TreestampsConfig.normalize_config(
            resolved
        ) == TreestampsConfig.normalize_config(expected)


class TestInvalidation:
    """Which changes discard recorded timestamps."""

    STAMP_TS = 100.0

    def _stamp(self, media: Path, walk: Walk) -> None:
        stamps = _stamps(walk)
        stamps.set(media, media / "a.mkv", self.STAMP_TS)
        stamps.dumpf()

    def _loaded_timestamp(self, media: Path, walk: Walk) -> float | None:
        return _stamps(walk).get_timestamp(media, media / "a.mkv")

    def test_same_config_keeps_timestamps(self, tmp_path) -> None:
        """An unchanged run reuses its stamps."""
        media = tmp_path / "media"
        self._stamp(media, _walk(media))
        assert self._loaded_timestamp(media, _walk(media)) == self.STAMP_TS

    def test_changed_option_invalidates(self, tmp_path) -> None:
        """A changed recorded option discards the stamps."""
        media = tmp_path / "media"
        self._stamp(media, _walk(media))
        assert self._loaded_timestamp(media, _walk(media, "--no-title")) is None

    def test_added_key_at_default_keeps_timestamps(self, tmp_path) -> None:
        """A stamp file predating a recorded key is valid at that key's default."""
        media = tmp_path / "media"
        self._stamp(media, _walk(media))
        # Simulate a file written before `ignore` joined the recorded keys.
        stamp = media / TS_FN
        text = "\n".join(
            line for line in stamp.read_text().split("\n") if "ignore" not in line
        )
        stamp.write_text(text)
        assert self._loaded_timestamp(media, _walk(media)) == self.STAMP_TS

    def test_dir_config_comment_edit_keeps_timestamps(self, tmp_path) -> None:
        """Only option values matter to the fingerprint, not formatting."""
        media = tmp_path / "media"
        media.mkdir(parents=True)
        sub = media / "sub"
        sub.mkdir()
        config = sub / ".nudebomb.yaml"
        config.write_text("nudebomb:\n  title: false\n")
        self._stamp(media, _walk(media))
        config.write_text("# a comment\nnudebomb:\n\n  title:   false\n")
        assert self._loaded_timestamp(media, _walk(media)) == self.STAMP_TS

    def test_dir_config_value_edit_invalidates(self, tmp_path) -> None:
        """An option value edit in a directory config discards the stamps."""
        media = tmp_path / "media"
        media.mkdir(parents=True)
        sub = media / "sub"
        sub.mkdir()
        config = sub / ".nudebomb.yaml"
        config.write_text("nudebomb:\n  title: false\n")
        self._stamp(media, _walk(media))
        config.write_text("nudebomb:\n  title: true\n")
        assert self._loaded_timestamp(media, _walk(media)) is None

    def test_no_dir_configs_hashes_to_empty_digest(self, tmp_path) -> None:
        """The fingerprint default must match a run with no config files."""
        media = tmp_path / "media"
        program_config = _stamps(_walk(media))[media]._config.program_config
        assert program_config is not None
        fingerprint = program_config["_dir_config_fingerprint"]
        # One root, hashed into the combining digest.
        expected = sha256(
            str(media).encode() + b"\0" + bytes.fromhex(sha256(b"").hexdigest())
        ).hexdigest()
        assert fingerprint == expected
