jobs:
  build:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run:
          command: docker-compose build nudebomb-build-builder
          name: Install Build Dependencies
      - run:
          command: docker-compose up --exit-code-from nudebomb-lint nudebomb-lint
          name: Lint
      - run:
          command: bin/create-output-dirs.sh
          name: Create Output Dirs
      - run:
          command: docker-compose up --exit-code-from nudebomb-test nudebomb-test
          name: Test
      - store_test_results:
          path: test-results/pytest
      - store_artifacts:
          path: test-results/coverage
      - run:
          command: docker-compose up --exit-code-from nudebomb-build nudebomb-build
          name: Build
      - persist_to_workspace:
          paths:
            - ./README.md
            - ./bin
            - ./dist
            - ./pyproject.toml
          root: .
  deploy:
    docker:
      - image: cimg/python:3.12
    steps:
      - attach_workspace:
          at: .
      - run:
          command: pip install poetry
          name: Install poetry
      - run:
          command: bin/publish-pypi.sh
          name: Publish Package to PyPi
version: 2.1
workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - pre-release
                - develop
                - main
                - /.*-ci/
      - deploy:
          filters:
            branches:
              only:
                - pre-release
                - main
          requires:
            - build
  version: 2.1
